name: List Files

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List files
        run: |
         git touch hi
         git add.
         git commit -m "dd"
         git push origin master
         
      
          
