name: List Files

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List files
        run: |
          ls -al
